issuer: https://accounts.google.com

# staging-enforce: ci-cve-scan-y3p1d12mopp7me1maq@staging-enforce-cd1e.iam.gserviceaccount.com (116393215694983881739)
# prod-images: TODO
subject_pattern: "(116393215694983881739)"

permissions:
  contents: read
